




.build/uno/src/monitor.cpp : src/monitor.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/monitor.ino[0m
	@/usr/local/Cellar/ino/0.3.6/libexec/bin/ino preproc  -o $@ $^


all : .build/uno/src/monitor.cpp
	@true

