




.build/leonardo/src/monitor.cpp : src/monitor.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/monitor.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/monitor.cpp
	@true

